export const ICONO_CATEGORIA_DEFAULT = '🏷';

export const ICONOS_CATEGORIA = [
	{ icono: '🛒', nombre: 'Supermercado' },
	{ icono: '⚡', nombre: 'Servicios' },
	{ icono: '🏠', nombre: 'Vivienda' },
	{ icono: '🏥', nombre: 'Salud' },
	{ icono: '🚌', nombre: 'Transporte' },
	{ icono: '📚', nombre: 'Educación' },
	{ icono: '🎬', nombre: 'Entretenimiento' },
	{ icono: '↔️', nombre: 'Transferencias' },
	{ icono: '💰', nombre: 'Ingresos' },
	{ icono: '👤', nombre: 'Personal' },
	{ icono: '💸', nombre: 'Impuestos' },
	{ icono: '📋', nombre: 'Otros' },
	{ icono: '🏷', nombre: 'Etiqueta' },
	{ icono: '🧾', nombre: 'Factura' },
	{ icono: '🛍️', nombre: 'Compras' },
	{ icono: '🍔', nombre: 'Comida' },
	{ icono: '🚗', nombre: 'Auto' },
	{ icono: '⛽', nombre: 'Combustible' },
	{ icono: '🏡', nombre: 'Hogar' },
	{ icono: '🔧', nombre: 'Mantenimiento' },
	{ icono: '📱', nombre: 'Tecnologia' },
	{ icono: '🎓', nombre: 'Estudio' },
	{ icono: '🎯', nombre: 'Objetivo' },
	{ icono: '🎁', nombre: 'Regalos' },
	{ icono: '✈️', nombre: 'Viajes' },
	{ icono: '🐶', nombre: 'Mascotas' },
	{ icono: '💼', nombre: 'Trabajo' },
	{ icono: '💳', nombre: 'Tarjeta' },
	{ icono: '💡', nombre: 'Herramientas' },
	{ icono: '🧘', nombre: 'Bienestar' },
	{ icono: '🚬', nombre: 'Cigarrillos/Snacks' },
];
